import Head from 'next/head'
import { useState } from 'react'

export default function Home () {
  const [value, setValue] = useState('')
  const [result, setResult] = useState({})
  const handleSearch = () => {
    fetch('/api/hello', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ value })
    })
      .then(res => res.json())
      .then(data => {
        setResult(data)
      })
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Main</h1>
        <input
          placeholder='Enter a word'
          onChange={(e) => {
            setValue(e.target.value)
          }}
        />
        <button onClick={handleSearch}>
          Search
        </button>
        {
          JSON.stringify(result)
        }
      </main>
    </>
  )
}
